#Site
title: 승민-블로그
description: This is 승민's home.
logo: favicon.png
url: tmdals8030.github.io
rss_url: /feed.xml

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Comment
comment:
  disqus: smin
  gitalk: true

# Website analytics
#google_analytics: UA-82494501-1

# Author information:
author:
  #resume: /resume
  name: 김승민     #the name of Blog section
  #about_me: 자기소개서 성장배경: 중학생 때 LUA로 스크립트를 작성 가능한 게임엔진을 몇 달간 사용해 본 적이 있었는데, 만들어낸 결과물이 만족스럽지 못해서 어떻게 하면 생각한 대로 구현하는 방법들을 공부해보았습니다. 이후에도 고등학생 때 Unity 게임엔진을 공부하면서 클라이언트 프로그래머를 희망하게 되었고, 대학도 컴퓨터공학과를 진학하게 되었습니다. 여러 가지 경험이 있었지만, 중학생 때의 경험이 특히 주변의 누구도 가르쳐주지 않았던 내용을 혼자서 배워보고자 노력했던 경험이기에 이후에 프로그래밍을 익히는 데 있어서 많은 영향을 끼친 것 같습니다. 장점: 저는 문제를 어떻게든 해결해보려는 엄청난 끈기를 가지고 있습니다. 이를 이용하여 예전에 Tippecanoe County의 보안관 사무실 애플리케이션의 초기 버전 개발 당시에 요구했던 인앱에서의 메일 전송 기능을 3일 내내 여러 가지 방법들을 시도하여 구현해보았습니다. 지원동기: 제가 회사에 지원해서 클라이언트를 개발하면서 좀 더 안정적인 클라이언트를 만들어보고 싶어서 지원하게 되었습니다. 이를 위해서는 컴퓨터 구조에 대한 전반적인 지식과 디자인 패턴, 자료 구조 등 여러 가지 기반이 필요하고 저는 이러한 내용을 학교뿐만이 아니라 개인적으로도 별도의 공부를 하였습니다.뒷받침하는 경험 기술

# Social Links
email:               a7965344@gmail.com
#google.plus:        username
#twitter:            username
facebook:            김승민
github:              tmdals8030
stackoverflow:      13048654/김승민   #from a "http://stackoverflow.com/users/123456/username" link
#linkedin:         
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile,.sass-cache,.DS_Store,.idea]
